// <auto-generated />
using System;
using GardenAssistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GardenAssistant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320080227_AddPlantCalendarEntities")]
    partial class AddPlantCalendarEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GardenAssistant.Data.Entities.Garden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_gardens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_gardens_user_id");

                    b.ToTable("gardens", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_guilds");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_guilds_user_id");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.GuildPlant", b =>
                {
                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("guild_id");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.HasKey("GuildId", "PlantId")
                        .HasName("pk_guild_plants");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_guild_plants_plant_id");

                    b.ToTable("guild_plants", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.HarvestReadiness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DaysFromSowing")
                        .HasColumnType("integer")
                        .HasColumnName("days_from_sowing");

                    b.Property<int?>("DaysFromTransplant")
                        .HasColumnType("integer")
                        .HasColumnName("days_from_transplant");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.HasKey("Id")
                        .HasName("pk_harvest_readiness");

                    b.HasIndex("PlantId")
                        .IsUnique()
                        .HasDatabaseName("ix_harvest_readiness_plant_id");

                    b.ToTable("harvest_readiness", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.HarvestReadinessCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CriterionType")
                        .HasColumnType("integer")
                        .HasColumnName("criterion_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("HarvestReadinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("harvest_readiness_id");

                    b.HasKey("Id")
                        .HasName("pk_harvest_readiness_criteria");

                    b.HasIndex("HarvestReadinessId")
                        .HasDatabaseName("ix_harvest_readiness_criteria_harvest_readiness_id");

                    b.ToTable("harvest_readiness_criteria", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<string>("Family")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("family");

                    b.Property<bool>("FrostSensitive")
                        .HasColumnType("boolean")
                        .HasColumnName("frost_sensitive");

                    b.Property<string>("Genus")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("genus");

                    b.Property<int?>("HeightAtMaturityCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_at_maturity_cm");

                    b.Property<int>("LifeCycle")
                        .HasColumnType("integer")
                        .HasColumnName("life_cycle");

                    b.Property<int?>("MaxAltitudeM")
                        .HasColumnType("integer")
                        .HasColumnName("max_altitude_m");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("PropagationMethod")
                        .HasColumnType("integer")
                        .HasColumnName("propagation_method");

                    b.Property<int>("RootDepth")
                        .HasColumnType("integer")
                        .HasColumnName("root_depth");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("scientific_name");

                    b.Property<int>("SunRequirement")
                        .HasColumnType("integer")
                        .HasColumnName("sun_requirement");

                    b.Property<int>("WaterNeeds")
                        .HasColumnType("integer")
                        .HasColumnName("water_needs");

                    b.HasKey("Id")
                        .HasName("pk_plants");

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.PlantAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<int>("HalfMonthEnd")
                        .HasColumnType("integer")
                        .HasColumnName("half_month_end");

                    b.Property<int>("HalfMonthStart")
                        .HasColumnType("integer")
                        .HasColumnName("half_month_start");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.HasKey("Id")
                        .HasName("pk_plant_actions");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_plant_actions_plant_id");

                    b.ToTable("plant_actions", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.PlantAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_level");

                    b.Property<int>("DistanceEffect")
                        .HasColumnType("integer")
                        .HasColumnName("distance_effect");

                    b.Property<int>("Effect")
                        .HasColumnType("integer")
                        .HasColumnName("effect");

                    b.Property<int>("Mechanism")
                        .HasColumnType("integer")
                        .HasColumnName("mechanism");

                    b.Property<string>("Notes")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("SourcePlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_plant_id");

                    b.Property<Guid>("TargetPlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_plant_id");

                    b.HasKey("Id")
                        .HasName("pk_plant_associations");

                    b.HasIndex("TargetPlantId")
                        .HasDatabaseName("ix_plant_associations_target_plant_id");

                    b.HasIndex("SourcePlantId", "TargetPlantId", "Mechanism")
                        .IsUnique()
                        .HasDatabaseName("ix_plant_associations_source_plant_id_target_plant_id_mechanism");

                    b.ToTable("plant_associations", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.PlantIntrinsicMechanism", b =>
                {
                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<int>("Mechanism")
                        .HasColumnType("integer")
                        .HasColumnName("mechanism");

                    b.HasKey("PlantId", "Mechanism")
                        .HasName("pk_plant_intrinsic_mechanisms");

                    b.ToTable("plant_intrinsic_mechanisms", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.Planting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("GardenId")
                        .HasColumnType("uuid")
                        .HasColumnName("garden_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_plantings");

                    b.HasIndex("GardenId")
                        .HasDatabaseName("ix_plantings_garden_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_plantings_user_id");

                    b.ToTable("plantings", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.PlantingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActualHarvestDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_harvest_date");

                    b.Property<int?>("Layer")
                        .HasColumnType("integer")
                        .HasColumnName("layer");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PlannedHarvestDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_harvest_date");

                    b.Property<DateOnly?>("PlannedSowDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_sow_date");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<Guid>("PlantingId")
                        .HasColumnType("uuid")
                        .HasColumnName("planting_id");

                    b.Property<float?>("PositionX")
                        .HasColumnType("real")
                        .HasColumnName("position_x");

                    b.Property<float?>("PositionY")
                        .HasColumnType("real")
                        .HasColumnName("position_y");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_planting_entries");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_planting_entries_plant_id");

                    b.HasIndex("PlantingId")
                        .HasDatabaseName("ix_planting_entries_planting_id");

                    b.ToTable("planting_entries", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "admin@gardenassistant.local"
                        });
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.UserPlant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at_utc");

                    b.HasKey("UserId", "PlantId")
                        .HasName("pk_user_plants");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("ix_user_plants_plant_id");

                    b.ToTable("user_plants", (string)null);
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.Garden", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gardens_users_user_id");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.Guild", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_guilds_users_user_id");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.GuildPlant", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_plants_guilds_guild_id");

                    b.HasOne("GardenAssistant.Data.Entities.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guild_plants_plants_plant_id");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.HarvestReadiness", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.Plant", "Plant")
                        .WithOne("HarvestReadiness")
                        .HasForeignKey("GardenAssistant.Data.Entities.HarvestReadiness", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_harvest_readiness_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.HarvestReadinessCriterion", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.HarvestReadiness", "HarvestReadiness")
                        .WithMany("Criteria")
                        .HasForeignKey("HarvestReadinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_harvest_readiness_criteria_harvest_readiness_harvest_readin");

                    b.Navigation("HarvestReadiness");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.PlantAction", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.Plant", "Plant")
                        .WithMany("Actions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plant_actions_plants_plant_id");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.PlantAssociation", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.Plant", null)
                        .WithMany()
                        .HasForeignKey("SourcePlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plant_associations_plants_source_plant_id");

                    b.HasOne("GardenAssistant.Data.Entities.Plant", null)
                        .WithMany()
                        .HasForeignKey("TargetPlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plant_associations_plants_target_plant_id");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.PlantIntrinsicMechanism", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.Plant", null)
                        .WithMany("IntrinsicMechanisms")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plant_intrinsic_mechanisms_plants_plant_id");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.Planting", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.Garden", null)
                        .WithMany()
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plantings_gardens_garden_id");

                    b.HasOne("GardenAssistant.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plantings_users_user_id");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.PlantingEntry", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_planting_entries_plants_plant_id");

                    b.HasOne("GardenAssistant.Data.Entities.Planting", null)
                        .WithMany()
                        .HasForeignKey("PlantingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planting_entries_plantings_planting_id");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.UserPlant", b =>
                {
                    b.HasOne("GardenAssistant.Data.Entities.Plant", null)
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_plants_plants_plant_id");

                    b.HasOne("GardenAssistant.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_plants_users_user_id");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.HarvestReadiness", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("GardenAssistant.Data.Entities.Plant", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("HarvestReadiness");

                    b.Navigation("IntrinsicMechanisms");
                });
#pragma warning restore 612, 618
        }
    }
}
